# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre del alumno:', max_length=50)),
                ('phone', models.CharField(help_text='Ingrese el Numero del Alumno:', max_length=10)),
                ('sex', models.CharField(help_text='Ingrse el Tipo de Sexo', max_length=1)),
                ('PubDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
